name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}" > credentials.json
      shell: bash
    - name: Build and Deploy
      run: |
        # Your build and deploy commands here
      env:
        GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
